alertmanager:
  enabled: false
grafana:
  enabled: true
  adminPassword: prom-operator
  ingress:
    enabled: true
    hosts:
      - your.domain
  persistence:
    type: pvc
    enabled: true
    # storageClassName: default
    accessModes:
    - ReadWriteOnce
    size: 1Gi
    # annotations: {}
    finalizers:
    - kubernetes.io/pvc-protection
  deploymentStrategy:
    type: Recreate
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
prometheus:
  enabled: true
  prometheusSpec:
    retention: 10d
    retentionSize: 10GiB
    storageSpec:
     volumeClaimTemplate:
       spec:
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 11Gi