grafana:
  enabled: true
  adminPassword: prom-operator
  defaultDashboardsTimezone: browser
  ingress:
    enabled: true
    hosts:
      - your.domain
  persistence:
    type: pvc
    enabled: true
    # storageClassName: default
    accessModes:
    - ReadWriteOnce
    size: 1Gi
    # annotations: {}
    finalizers:
    - kubernetes.io/pvc-protection
  deploymentStrategy:
    type: Recreate
prometheus:
  enabled: true
  prometheusSpec:
    retention: 30d
    retentionSize: 10GiB
    storageSpec:
     volumeClaimTemplate:
       spec:
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 11Gi
kubeStateMetrics:
  enabled: true
  collectors:
  - pods
nodeExporter:
  enabled: false
kubeApiServer:
  enabled: false
kubeDns:
  enabled: false
kubeProxy:
  enabled: false
coreDns:
  enabled: false
kubeEtcd:
  enabled: false
alertmanager:
  enabled: false
kubeScheduler:
  enabled: false